INSERT INTO DIAGNOSTICO (IdDiagnostico, TratamentoRecomendado, RemediosReceitados, Observacoes, IdCon) VALUES
(63, 'Uso de óculos', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 44),
(64, 'Revisão médica', 'Antidepressivos', 'Revisão em 3 meses', 45),
(65, 'Correção de miopia', 'Atenolol', 'Retorno em 30 dias', 46),
(66, 'Ajuste de medicamentos', 'Novos medicamentos', 'Revisão em 3 meses', 47),
(67, 'Controle hormonal', 'Óculos novos', 'Consulta com nutricionista', 48),
(68, 'Ajuste de medicamentos', 'Anti-inflamatórios', 'Retorno em 30 dias', 49),
(69, 'Dieta especial', 'Insulina', 'Retorno em 30 dias', 50),
(70, 'Iniciar tratamento', 'Suplementos', 'Retorno em 15 dias', 51),
(71, 'Correção de miopia', 'Cremes dermatológicos', 'Monitorar glicemia', 52),
(72, 'Ajuste de medicação', 'Anti-inflamatórios', 'Retorno em 30 dias', 53),
(73, 'Revisão médica', 'Suplementos vitamínicos', 'Monitorar glicemia', 54),
(74, 'Controle hormonal', 'Óculos novos', 'Revisão em 3 meses', 55),
(75, 'Terapia ocupacional', 'Atenolol', 'Sessões semanais', 56),
(76, 'Novo óculos', 'Insulina', 'Sessões semanais', 57),
(77, 'Dieta balanceada', 'Lentes corretivas', 'Verificar pressão diariamente', 58),
(78, 'Sessões de terapia', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 59),
(79, 'Ajuste de medicação', 'Antidepressivos', 'Sessões semanais', 60),
(80, 'Sessões de terapia', 'Hormônios', 'Evitar esforços físicos', 61),
(81, 'Dieta balanceada', 'Suplementos vitamínicos', 'Retorno em 15 dias', 62),
(82, 'Fisioterapia', 'Medicamentos para ansiedade', 'Monitorar glicemia', 63),
(83, 'Uso de óculos', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 64),
(84, 'Terapia intensiva', 'Atenolol', 'Evitar esforços físicos', 65),
(85, 'Avaliação psicológica', 'Anti-inflamatórios', 'Evitar esforços físicos', 66),
(86, 'Fisioterapia', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 67),
(87, 'Iniciar tratamento', 'Antidepressivos', 'Evitar esforços físicos', 68),
(88, 'Dieta balanceada', 'Anti-inflamatórios', 'Avaliar em 60 dias', 69),
(89, 'Controle de diabetes', 'Atenolol', 'Retorno em 15 dias', 70),
(90, 'Avaliação psicológica', 'Antidepressivos', 'Consulta com nutricionista', 71),
(91, 'Dieta especial', 'Suplementos', 'Aplicar duas vezes ao dia', 72),
(92, 'Sessões de terapia', 'Anti-inflamatórios', 'Evitar esforços físicos', 73),
(93, 'Dieta especial', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 74),
(94, 'Terapia intensiva', 'Novos medicamentos', 'Consulta com nutricionista', 75),
(95, 'Revisão do tratamento', 'Atenolol', 'Evitar esforços físicos', 76),
(96, 'Fisioterapia', 'Antidepressivos', 'Revisão em 6 meses', 77),
(97, 'Controle de dieta', 'Insulina', 'Consulta com nutricionista', 78),
(98, 'Correção de miopia', 'Suplementos', 'Monitorar glicemia', 79),
(99, 'Fisioterapia', 'Cremes dermatológicos', 'Retorno em 15 dias', 80),
(100, 'Dieta balanceada', 'Lentes corretivas', 'Revisão em 3 meses', 81),
(101, 'Controle de diabetes', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 82),
(102, 'Dieta especial', 'Insulina', 'Revisão em 3 meses', 83),
(103, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Retorno em 30 dias', 84),
(104, 'Terapia intensiva', 'Lentes corretivas', 'Aplicar duas vezes ao dia', 85),
(105, 'Controle hormonal', 'Antidepressivos', 'Avaliar em 60 dias', 86),
(106, 'Sessões de terapia', 'Novos medicamentos', 'Monitorar glicemia', 87),
(107, 'Fisioterapia', 'Suplementos', 'Verificar pressão diariamente', 88),
(108, 'Controle de diabetes', 'Antidepressivos', 'Retorno em 15 dias', 89),
(109, 'Revisão médica', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 90),
(110, 'Sessões de terapia', 'Suplementos', 'Revisão em 3 meses', 91),
(111, 'Dieta balanceada', 'Insulina', 'Consulta com nutricionista', 92),
(112, 'Uso de óculos', 'Anti-inflamatórios', 'Avaliar em 60 dias', 93),
(113, 'Sessões de terapia', 'Novos medicamentos', 'Evitar esforços físicos', 94),
(114, 'Controle hormonal', 'Suplementos vitamínicos', 'Consulta com nutricionista', 95),
(115, 'Sessões de terapia', 'Anti-inflamatórios', 'Revisão em 6 meses', 96),
(116, 'Novo óculos', 'Anti-inflamatórios', 'Evitar esforços físicos', 97),
(117, 'Terapia ocupacional', 'Suplementos vitamínicos', 'Monitorar glicemia', 98),
(118, 'Novo óculos', 'Suplementos', 'Evitar esforços físicos', 99),
(119, 'Fisioterapia', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 100),
(120, 'Controle de dieta', 'Atenolol', 'Retorno em 15 dias', 101),
(121, 'Ajuste de medicamentos', 'Óculos novos', 'Consulta com nutricionista', 102),
(122, 'Revisão do tratamento', 'Anti-inflamatórios', 'Avaliar em 60 dias', 103),
(123, 'Uso de óculos', 'Atenolol', 'Verificar pressão diariamente', 104),
(124, 'Controle hormonal', 'Suplementos', 'Revisão em 6 meses', 105),
(125, 'Avaliação psicológica', 'Suplementos vitamínicos', 'Evitar esforços físicos', 106),
(126, 'Uso de óculos', 'Atenolol', 'Revisão em 3 meses', 107),
(127, 'Controle hormonal', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 108),
(128, 'Avaliação psicológica', 'Antidepressivos', 'Aplicar duas vezes ao dia', 109),
(129, 'Terapia ocupacional', 'Anti-inflamatórios', 'Evitar esforços físicos', 110),
(130, 'Novo óculos', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 111),
(131, 'Fisioterapia', 'Anti-inflamatórios', 'Evitar esforços físicos', 112),
(132, 'Dieta especial', 'Óculos novos', 'Retorno em 30 dias', 113),
(133, 'Revisão médica', 'Insulina', 'Consulta com nutricionista', 114),
(134, 'Controle hormonal', 'Anti-inflamatórios', 'Verificar pressão diariamente', 115),
(135, 'Avaliação psicológica', 'Atenolol', 'Verificar pressão diariamente', 116),
(136, 'Fisioterapia', 'Insulina', 'Retorno em 15 dias', 117),
(137, 'Fisioterapia', 'Lentes corretivas', 'Retorno em 15 dias', 118),
(138, 'Novo óculos', 'Cremes dermatológicos', 'Avaliar em 60 dias', 119),
(139, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 120),
(140, 'Dieta balanceada', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 121),
(141, 'Fisioterapia', 'Hormônios', 'Evitar esforços físicos', 122),
(142, 'Controle de diabetes', 'Óculos novos', 'Avaliar em 60 dias', 123),
(143, 'Terapia ocupacional', 'Óculos novos', 'Aplicar duas vezes ao dia', 124),
(144, 'Controle hormonal', 'Atenolol', 'Verificar pressão diariamente', 125),
(145, 'Dieta especial', 'Hormônios', 'Sessões semanais', 126),
(146, 'Novo óculos', 'Insulina', 'Evitar esforços físicos', 127),
(147, 'Controle de dieta', 'Medicamentos para ansiedade', 'Sessões semanais', 128),
(148, 'Revisão do tratamento', 'Anti-inflamatórios', 'Consulta com nutricionista', 129),
(149, 'Ajuste de medicamentos', 'Novos medicamentos', 'Consulta com nutricionista', 130),
(150, 'Ajuste de medicação', 'Lentes corretivas', 'Aplicar duas vezes ao dia', 131),
(151, 'Terapia intensiva', 'Anti-inflamatórios', 'Revisão em 6 meses', 132),
(152, 'Controle hormonal', 'Atenolol', 'Aplicar duas vezes ao dia', 133),
(153, 'Correção de miopia', 'Novos medicamentos', 'Avaliar em 60 dias', 134),
(154, 'Controle hormonal', 'Óculos novos', 'Consulta com nutricionista', 135),
(155, 'Controle hormonal', 'Insulina', 'Retorno em 30 dias', 136),
(156, 'Controle de diabetes', 'Hormônios', 'Revisão em 6 meses', 137),
(157, 'Novo óculos', 'Óculos novos', 'Revisão em 6 meses', 138),
(158, 'Fisioterapia', 'Insulina', 'Consulta com nutricionista', 139),
(159, 'Revisão do tratamento', 'Anti-inflamatórios', 'Sessões semanais', 140),
(160, 'Dieta balanceada', 'Novos medicamentos', 'Retorno em 15 dias', 141),
(161, 'Correção de miopia', 'Suplementos vitamínicos', 'Evitar esforços físicos', 142),
(162, 'Iniciar tratamento', 'Óculos novos', 'Aplicar duas vezes ao dia', 143),
(163, 'Ajuste de medicação', 'Insulina', 'Retorno em 15 dias', 144),
(164, 'Uso de óculos', 'Novos medicamentos', 'Retorno em 30 dias', 145),
(165, 'Controle de diabetes', 'Suplementos', 'Retorno em 15 dias', 146),
(166, 'Sessões de terapia', 'Hormônios', 'Avaliar em 60 dias', 147),
(167, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 148),
(168, 'Dieta especial', 'Antidepressivos', 'Aplicar duas vezes ao dia', 149),
(169, 'Controle de dieta', 'Atenolol', 'Evitar esforços físicos', 150),
(170, 'Dieta especial', 'Cremes dermatológicos', 'Monitorar glicemia', 151),
(171, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 152),
(172, 'Terapia ocupacional', 'Antidepressivos', 'Verificar pressão diariamente', 153),
(173, 'Avaliação psicológica', 'Óculos novos', 'Consulta com nutricionista', 154),
(174, 'Controle de dieta', 'Anti-inflamatórios', 'Revisão em 6 meses', 155),
(175, 'Fisioterapia', 'Lentes corretivas', 'Retorno em 30 dias', 156),
(176, 'Controle hormonal', 'Hormônios', 'Avaliar em 60 dias', 157),
(177, 'Correção de miopia', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 158),
(178, 'Dieta especial', 'Cremes dermatológicos', 'Avaliar em 60 dias', 159),
(179, 'Terapia intensiva', 'Suplementos vitamínicos', 'Evitar esforços físicos', 160),
(180, 'Uso de óculos', 'Anti-inflamatórios', 'Revisão em 6 meses', 161),
(181, 'Controle de dieta', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 162),
(182, 'Dieta especial', 'Antidepressivos', 'Evitar esforços físicos', 163),
(183, 'Fisioterapia', 'Óculos novos', 'Monitorar glicemia', 164),
(184, 'Dieta balanceada', 'Atenolol', 'Verificar pressão diariamente', 165),
(185, 'Controle hormonal', 'Lentes corretivas', 'Verificar pressão diariamente', 166),
(186, 'Controle de diabetes', 'Antidepressivos', 'Monitorar glicemia', 167),
(187, 'Terapia intensiva', 'Suplementos vitamínicos', 'Retorno em 15 dias', 168),
(188, 'Revisão médica', 'Suplementos', 'Verificar pressão diariamente', 169),
(189, 'Ajuste de medicação', 'Antidepressivos', 'Revisão em 3 meses', 170),
(190, 'Fisioterapia', 'Óculos novos', 'Consulta com nutricionista', 171),
(191, 'Dieta balanceada', 'Anti-inflamatórios', 'Consulta com nutricionista', 172),
(192, 'Controle hormonal', 'Óculos novos', 'Avaliar em 60 dias', 173),
(193, 'Ajuste de medicação', 'Insulina', 'Retorno em 15 dias', 174),
(194, 'Dieta especial', 'Óculos novos', 'Aplicar duas vezes ao dia', 175),
(195, 'Ajuste de medicação', 'Óculos novos', 'Revisão em 3 meses', 176),
(196, 'Ajuste de medicamentos', 'Medicamentos para ansiedade', 'Sessões semanais', 177),
(197, 'Controle de diabetes', 'Insulina', 'Sessões semanais', 178),
(198, 'Controle de diabetes', 'Cremes dermatológicos', 'Revisão em 6 meses', 179),
(199, 'Sessões de terapia', 'Antidepressivos', 'Consulta com nutricionista', 180),
(200, 'Controle de dieta', 'Medicamentos para ansiedade', 'Monitorar glicemia', 181),
(201, 'Terapia ocupacional', 'Insulina', 'Aplicar duas vezes ao dia', 182),
(202, 'Terapia ocupacional', 'Suplementos', 'Retorno em 30 dias', 183),
(203, 'Terapia ocupacional', 'Antidepressivos', 'Verificar pressão diariamente', 184),
(204, 'Controle de diabetes', 'Suplementos', 'Retorno em 30 dias', 185),
(205, 'Dieta especial', 'Suplementos', 'Avaliar em 60 dias', 186),
(206, 'Controle hormonal', 'Cremes dermatológicos', 'Consulta com nutricionista', 187),
(207, 'Terapia intensiva', 'Novos medicamentos', 'Revisão em 3 meses', 188),
(208, 'Avaliação psicológica', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 189),
(209, 'Controle hormonal', 'Atenolol', 'Revisão em 6 meses', 190),
(210, 'Ajuste de medicamentos', 'Lentes corretivas', 'Consulta com nutricionista', 191),
(211, 'Revisão médica', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 192),
(212, 'Fisioterapia', 'Novos medicamentos', 'Sessões semanais', 193),
(213, 'Controle hormonal', 'Cremes dermatológicos', 'Revisão em 6 meses', 194),
(214, 'Controle de dieta', 'Antidepressivos', 'Revisão em 6 meses', 195),
(215, 'Controle hormonal', 'Suplementos', 'Monitorar glicemia', 196),
(216, 'Novo óculos', 'Óculos novos', 'Verificar pressão diariamente', 197),
(217, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 198),
(218, 'Controle hormonal', 'Hormônios', 'Evitar esforços físicos', 199),
(219, 'Sessões de terapia', 'Novos medicamentos', 'Retorno em 30 dias', 200),
(220, 'Terapia ocupacional', 'Cremes dermatológicos', 'Revisão em 3 meses', 201),
(221, 'Controle hormonal', 'Novos medicamentos', 'Consulta com nutricionista', 202),
(222, 'Novo óculos', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 203),
(223, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 204),
(224, 'Avaliação psicológica', 'Atenolol', 'Sessões semanais', 205),
(225, 'Avaliação psicológica', 'Suplementos vitamínicos', 'Sessões semanais', 206),
(226, 'Revisão médica', 'Suplementos', 'Avaliar em 60 dias', 207),
(227, 'Revisão do tratamento', 'Insulina', 'Avaliar em 60 dias', 208),
(228, 'Controle de dieta', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 209),
(229, 'Ajuste de medicamentos', 'Novos medicamentos', 'Verificar pressão diariamente', 210),
(230, 'Controle de diabetes', 'Insulina', 'Revisão em 3 meses', 211),
(231, 'Avaliação psicológica', 'Lentes corretivas', 'Sessões semanais', 212),
(232, 'Revisão do tratamento', 'Novos medicamentos', 'Evitar esforços físicos', 213),
(233, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 214),
(234, 'Avaliação psicológica', 'Anti-inflamatórios', 'Monitorar glicemia', 215),
(235, 'Fisioterapia', 'Insulina', 'Evitar esforços físicos', 216),
(236, 'Ajuste de medicamentos', 'Hormônios', 'Monitorar glicemia', 217),
(237, 'Sessões de terapia', 'Suplementos', 'Avaliar em 60 dias', 218),
(238, 'Ajuste de medicação', 'Insulina', 'Monitorar glicemia', 219),
(239, 'Controle de dieta', 'Óculos novos', 'Retorno em 30 dias', 220),
(240, 'Controle de dieta', 'Novos medicamentos', 'Evitar esforços físicos', 221),
(241, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Sessões semanais', 222),
(242, 'Terapia intensiva', 'Hormônios', 'Aplicar duas vezes ao dia', 223),
(243, 'Correção de miopia', 'Cremes dermatológicos', 'Retorno em 30 dias', 224),
(244, 'Controle de dieta', 'Atenolol', 'Retorno em 15 dias', 225),
(245, 'Controle hormonal', 'Óculos novos', 'Revisão em 3 meses', 226),
(246, 'Sessões de terapia', 'Suplementos', 'Revisão em 6 meses', 227),
(247, 'Controle de dieta', 'Anti-inflamatórios', 'Sessões semanais', 228),
(248, 'Revisão médica', 'Antidepressivos', 'Verificar pressão diariamente', 229),
(249, 'Uso de óculos', 'Medicamentos para ansiedade', 'Monitorar glicemia', 230),
(250, 'Revisão médica', 'Cremes dermatológicos', 'Retorno em 15 dias', 231),
(251, 'Avaliação psicológica', 'Atenolol', 'Consulta com nutricionista', 232),
(252, 'Controle hormonal', 'Novos medicamentos', 'Evitar esforços físicos', 233),
(253, 'Ajuste de medicamentos', 'Insulina', 'Retorno em 15 dias', 234),
(254, 'Controle hormonal', 'Insulina', 'Verificar pressão diariamente', 235),
(255, 'Controle hormonal', 'Insulina', 'Verificar pressão diariamente', 236),
(256, 'Sessões de terapia', 'Atenolol', 'Verificar pressão diariamente', 237),
(257, 'Controle hormonal', 'Novos medicamentos', 'Revisão em 6 meses', 238),
(258, 'Controle hormonal', 'Insulina', 'Consulta com nutricionista', 239),
(259, 'Controle hormonal', 'Atenolol', 'Revisão em 6 meses', 240),
(260, 'Ajuste de medicamentos', 'Hormônios', 'Retorno em 30 dias', 241),
(261, 'Dieta especial', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 242),
(262, 'Terapia intensiva', 'Atenolol', 'Evitar esforços físicos', 243),
(263, 'Controle hormonal', 'Suplementos', 'Consulta com nutricionista', 244),
(264, 'Revisão do tratamento', 'Anti-inflamatórios', 'Verificar pressão diariamente', 245),
(265, 'Ajuste de medicamentos', 'Anti-inflamatórios', 'Verificar pressão diariamente', 246),
(266, 'Sessões de terapia', 'Novos medicamentos', 'Evitar esforços físicos', 247),
(267, 'Ajuste de medicação', 'Antidepressivos', 'Aplicar duas vezes ao dia', 248),
(268, 'Terapia intensiva', 'Lentes corretivas', 'Revisão em 6 meses', 249),
(269, 'Revisão do tratamento', 'Óculos novos', 'Retorno em 15 dias', 250),
(270, 'Dieta balanceada', 'Óculos novos', 'Verificar pressão diariamente', 251),
(271, 'Uso de óculos', 'Cremes dermatológicos', 'Evitar esforços físicos', 252),
(272, 'Iniciar tratamento', 'Anti-inflamatórios', 'Revisão em 6 meses', 253),
(273, 'Revisão médica', 'Insulina', 'Consulta com nutricionista', 254),
(274, 'Terapia intensiva', 'Novos medicamentos', 'Avaliar em 60 dias', 255),
(275, 'Controle de dieta', 'Novos medicamentos', 'Retorno em 15 dias', 256),
(276, 'Correção de miopia', 'Lentes corretivas', 'Revisão em 3 meses', 257),
(277, 'Sessões de terapia', 'Cremes dermatológicos', 'Consulta com nutricionista', 258),
(278, 'Correção de miopia', 'Atenolol', 'Aplicar duas vezes ao dia', 259),
(279, 'Ajuste de medicamentos', 'Hormônios', 'Aplicar duas vezes ao dia', 260),
(280, 'Dieta especial', 'Suplementos', 'Monitorar glicemia', 261),
(281, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Aplicar duas vezes ao dia', 262),
(282, 'Iniciar tratamento', 'Anti-inflamatórios', 'Retorno em 30 dias', 263),
(283, 'Controle de diabetes', 'Antidepressivos', 'Revisão em 6 meses', 264),
(284, 'Controle hormonal', 'Cremes dermatológicos', 'Verificar pressão diariamente', 265),
(285, 'Dieta balanceada', 'Antidepressivos', 'Monitorar glicemia', 266),
(286, 'Fisioterapia', 'Suplementos vitamínicos', 'Retorno em 15 dias', 267),
(287, 'Terapia intensiva', 'Suplementos', 'Retorno em 30 dias', 268),
(288, 'Avaliação psicológica', 'Novos medicamentos', 'Revisão em 6 meses', 269),
(289, 'Controle hormonal', 'Anti-inflamatórios', 'Verificar pressão diariamente', 270),
(290, 'Dieta balanceada', 'Hormônios', 'Sessões semanais', 271),
(291, 'Controle de diabetes', 'Atenolol', 'Sessões semanais', 272),
(292, 'Controle de dieta', 'Suplementos', 'Retorno em 15 dias', 273),
(293, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Monitorar glicemia', 274),
(294, 'Sessões de terapia', 'Óculos novos', 'Sessões semanais', 275),
(295, 'Iniciar tratamento', 'Suplementos', 'Monitorar glicemia', 276),
(296, 'Controle hormonal', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 277),
(297, 'Fisioterapia', 'Lentes corretivas', 'Verificar pressão diariamente', 278),
(298, 'Correção de miopia', 'Suplementos', 'Monitorar glicemia', 279),
(299, 'Controle hormonal', 'Óculos novos', 'Verificar pressão diariamente', 280),
(300, 'Controle hormonal', 'Antidepressivos', 'Retorno em 15 dias', 281),
(301, 'Controle hormonal', 'Lentes corretivas', 'Verificar pressão diariamente', 282),
(302, 'Revisão do tratamento', 'Atenolol', 'Verificar pressão diariamente', 283),
(303, 'Iniciar tratamento', 'Insulina', 'Aplicar duas vezes ao dia', 284),
(304, 'Ajuste de medicamentos', 'Suplementos', 'Sessões semanais', 285),
(305, 'Controle hormonal', 'Óculos novos', 'Monitorar glicemia', 286),
(306, 'Dieta especial', 'Cremes dermatológicos', 'Revisão em 3 meses', 287),
(307, 'Avaliação psicológica', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 288),
(308, 'Correção de miopia', 'Novos medicamentos', 'Consulta com nutricionista', 289),
(309, 'Avaliação psicológica', 'Insulina', 'Avaliar em 60 dias', 290),
(310, 'Terapia ocupacional', 'Anti-inflamatórios', 'Evitar esforços físicos', 291),
(311, 'Correção de miopia', 'Antidepressivos', 'Retorno em 30 dias', 292),
(312, 'Ajuste de medicamentos', 'Anti-inflamatórios', 'Evitar esforços físicos', 293),
(313, 'Revisão médica', 'Hormônios', 'Revisão em 3 meses', 294),
(314, 'Dieta especial', 'Novos medicamentos', 'Revisão em 6 meses', 295),
(315, 'Avaliação psicológica', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 296),
(316, 'Uso de óculos', 'Antidepressivos', 'Revisão em 3 meses', 297),
(317, 'Revisão do tratamento', 'Atenolol', 'Verificar pressão diariamente', 298),
(318, 'Ajuste de medicação', 'Novos medicamentos', 'Revisão em 3 meses', 299),
(319, 'Sessões de terapia', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 300),
(320, 'Fisioterapia', 'Novos medicamentos', 'Avaliar em 60 dias', 301),
(321, 'Controle de diabetes', 'Insulina', 'Consulta com nutricionista', 302),
(322, 'Sessões de terapia', 'Atenolol', 'Avaliar em 60 dias', 303),
(323, 'Dieta balanceada', 'Atenolol', 'Consulta com nutricionista', 304),
(324, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Revisão em 3 meses', 305),
(325, 'Dieta balanceada', 'Insulina', 'Evitar esforços físicos', 306),
(326, 'Sessões de terapia', 'Atenolol', 'Revisão em 3 meses', 307),
(327, 'Controle de dieta', 'Novos medicamentos', 'Revisão em 3 meses', 308),
(328, 'Sessões de terapia', 'Insulina', 'Sessões semanais', 309),
(329, 'Terapia intensiva', 'Lentes corretivas', 'Monitorar glicemia', 310),
(330, 'Revisão do tratamento', 'Cremes dermatológicos', 'Consulta com nutricionista', 311),
(331, 'Terapia intensiva', 'Antidepressivos', 'Revisão em 6 meses', 312),
(332, 'Controle de diabetes', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 313),
(333, 'Controle hormonal', 'Suplementos vitamínicos', 'Consulta com nutricionista', 314),
(334, 'Dieta especial', 'Suplementos vitamínicos', 'Consulta com nutricionista', 315),
(335, 'Dieta especial', 'Lentes corretivas', 'Sessões semanais', 316),
(336, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Consulta com nutricionista', 317),
(337, 'Controle hormonal', 'Suplementos vitamínicos', 'Evitar esforços físicos', 318),
(338, 'Revisão médica', 'Cremes dermatológicos', 'Retorno em 30 dias', 319),
(339, 'Ajuste de medicação', 'Cremes dermatológicos', 'Revisão em 6 meses', 320),
(340, 'Terapia intensiva', 'Cremes dermatológicos', 'Consulta com nutricionista', 321),
(341, 'Controle de dieta', 'Suplementos', 'Verificar pressão diariamente', 322),
(342, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 323),
(343, 'Fisioterapia', 'Atenolol', 'Monitorar glicemia', 324),
(344, 'Avaliação psicológica', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 325),
(345, 'Terapia ocupacional', 'Lentes corretivas', 'Revisão em 3 meses', 326),
(346, 'Terapia intensiva', 'Suplementos vitamínicos', 'Consulta com nutricionista', 327),
(347, 'Controle hormonal', 'Antidepressivos', 'Evitar esforços físicos', 328),
(348, 'Terapia intensiva', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 329),
(349, 'Sessões de terapia', 'Cremes dermatológicos', 'Avaliar em 60 dias', 330),
(350, 'Controle hormonal', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 331),
(351, 'Avaliação psicológica', 'Atenolol', 'Retorno em 30 dias', 332),
(352, 'Sessões de terapia', 'Óculos novos', 'Sessões semanais', 333),
(353, 'Fisioterapia', 'Atenolol', 'Verificar pressão diariamente', 334),
(354, 'Dieta balanceada', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 335),
(355, 'Controle hormonal', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 336),
(356, 'Controle de dieta', 'Lentes corretivas', 'Retorno em 15 dias', 337),
(357, 'Dieta balanceada', 'Lentes corretivas', 'Retorno em 15 dias', 338),
(358, 'Dieta balanceada', 'Antidepressivos', 'Monitorar glicemia', 339),
(359, 'Correção de miopia', 'Cremes dermatológicos', 'Sessões semanais', 340),
(360, 'Ajuste de medicamentos', 'Suplementos', 'Revisão em 3 meses', 341),
(361, 'Ajuste de medicação', 'Anti-inflamatórios', 'Sessões semanais', 342),
(362, 'Iniciar tratamento', 'Suplementos vitamínicos', 'Evitar esforços físicos', 343),
(363, 'Fisioterapia', 'Insulina', 'Evitar esforços físicos', 344),
(364, 'Dieta balanceada', 'Cremes dermatológicos', 'Retorno em 15 dias', 345),
(365, 'Correção de miopia', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 346),
(366, 'Dieta balanceada', 'Suplementos', 'Aplicar duas vezes ao dia', 347),
(367, 'Ajuste de medicamentos', 'Insulina', 'Retorno em 30 dias', 348),
(368, 'Controle de diabetes', 'Suplementos', 'Aplicar duas vezes ao dia', 349),
(369, 'Terapia intensiva', 'Suplementos vitamínicos', 'Consulta com nutricionista', 350),
(370, 'Correção de miopia', 'Atenolol', 'Aplicar duas vezes ao dia', 351),
(371, 'Novo óculos', 'Antidepressivos', 'Retorno em 15 dias', 352),
(372, 'Sessões de terapia', 'Cremes dermatológicos', 'Revisão em 3 meses', 353),
(373, 'Terapia ocupacional', 'Insulina', 'Consulta com nutricionista', 354),
(374, 'Novo óculos', 'Antidepressivos', 'Sessões semanais', 355),
(375, 'Correção de miopia', 'Lentes corretivas', 'Sessões semanais', 356),
(376, 'Revisão do tratamento', 'Antidepressivos', 'Retorno em 30 dias', 357),
(377, 'Controle hormonal', 'Anti-inflamatórios', 'Verificar pressão diariamente', 358),
(378, 'Controle de diabetes', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 359),
(379, 'Novo óculos', 'Medicamentos para ansiedade', 'Monitorar glicemia', 360),
(380, 'Controle de dieta', 'Hormônios', 'Verificar pressão diariamente', 361),
(381, 'Ajuste de medicação', 'Anti-inflamatórios', 'Retorno em 15 dias', 362),
(382, 'Uso de óculos', 'Atenolol', 'Avaliar em 60 dias', 363),
(383, 'Revisão médica', 'Suplementos vitamínicos', 'Retorno em 15 dias', 364),
(384, 'Novo óculos', 'Cremes dermatológicos', 'Avaliar em 60 dias', 365),
(385, 'Ajuste de medicamentos', 'Óculos novos', 'Sessões semanais', 366),
(386, 'Uso de óculos', 'Novos medicamentos', 'Sessões semanais', 367),
(387, 'Novo óculos', 'Cremes dermatológicos', 'Revisão em 3 meses', 368),
(388, 'Iniciar tratamento', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 369),
(389, 'Uso de óculos', 'Novos medicamentos', 'Avaliar em 60 dias', 370),
(390, 'Dieta especial', 'Novos medicamentos', 'Verificar pressão diariamente', 371),
(391, 'Revisão do tratamento', 'Lentes corretivas', 'Verificar pressão diariamente', 372),
(392, 'Revisão médica', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 373),
(393, 'Revisão do tratamento', 'Atenolol', 'Aplicar duas vezes ao dia', 374),
(394, 'Revisão do tratamento', 'Hormônios', 'Sessões semanais', 375),
(395, 'Dieta especial', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 376),
(396, 'Dieta especial', 'Atenolol', 'Evitar esforços físicos', 377),
(397, 'Uso de óculos', 'Atenolol', 'Sessões semanais', 378),
(398, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Revisão em 3 meses', 379),
(399, 'Dieta especial', 'Cremes dermatológicos', 'Monitorar glicemia', 380),
(400, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Verificar pressão diariamente', 381),
(401, 'Controle de diabetes', 'Suplementos', 'Consulta com nutricionista', 382),
(402, 'Dieta balanceada', 'Atenolol', 'Retorno em 30 dias', 383),
(403, 'Dieta balanceada', 'Novos medicamentos', 'Avaliar em 60 dias', 384),
(404, 'Terapia intensiva', 'Cremes dermatológicos', 'Consulta com nutricionista', 385),
(405, 'Controle de dieta', 'Novos medicamentos', 'Revisão em 6 meses', 386),
(406, 'Novo óculos', 'Insulina', 'Verificar pressão diariamente', 387),
(407, 'Fisioterapia', 'Antidepressivos', 'Consulta com nutricionista', 388),
(408, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Aplicar duas vezes ao dia', 389),
(409, 'Avaliação psicológica', 'Novos medicamentos', 'Sessões semanais', 390),
(410, 'Ajuste de medicação', 'Antidepressivos', 'Evitar esforços físicos', 391),
(411, 'Revisão médica', 'Suplementos', 'Monitorar glicemia', 392),
(412, 'Novo óculos', 'Hormônios', 'Monitorar glicemia', 393),
(413, 'Dieta especial', 'Suplementos vitamínicos', 'Monitorar glicemia', 394),
(414, 'Terapia ocupacional', 'Suplementos', 'Retorno em 30 dias', 395),
(415, 'Terapia ocupacional', 'Cremes dermatológicos', 'Verificar pressão diariamente', 396),
(416, 'Controle hormonal', 'Lentes corretivas', 'Consulta com nutricionista', 397),
(417, 'Dieta especial', 'Novos medicamentos', 'Consulta com nutricionista', 398),
(418, 'Ajuste de medicamentos', 'Antidepressivos', 'Avaliar em 60 dias', 399),
(419, 'Revisão médica', 'Atenolol', 'Sessões semanais', 400),
(420, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Evitar esforços físicos', 401),
(421, 'Dieta balanceada', 'Insulina', 'Aplicar duas vezes ao dia', 402),
(422, 'Iniciar tratamento', 'Anti-inflamatórios', 'Avaliar em 60 dias', 403),
(423, 'Correção de miopia', 'Lentes corretivas', 'Consulta com nutricionista', 404),
(424, 'Terapia intensiva', 'Hormônios', 'Retorno em 15 dias', 405),
(425, 'Avaliação psicológica', 'Suplementos vitamínicos', 'Evitar esforços físicos', 406),
(426, 'Avaliação psicológica', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 407),
(427, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Retorno em 15 dias', 408),
(428, 'Novo óculos', 'Óculos novos', 'Revisão em 6 meses', 409),
(429, 'Novo óculos', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 410),
(430, 'Correção de miopia', 'Antidepressivos', 'Aplicar duas vezes ao dia', 411),
(431, 'Iniciar tratamento', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 412),
(432, 'Ajuste de medicação', 'Antidepressivos', 'Monitorar glicemia', 413),
(433, 'Novo óculos', 'Novos medicamentos', 'Verificar pressão diariamente', 414),
(434, 'Ajuste de medicamentos', 'Óculos novos', 'Avaliar em 60 dias', 415),
(435, 'Terapia ocupacional', 'Suplementos', 'Avaliar em 60 dias', 416),
(436, 'Terapia ocupacional', 'Cremes dermatológicos', 'Revisão em 6 meses', 417),
(437, 'Controle hormonal', 'Novos medicamentos', 'Consulta com nutricionista', 418),
(438, 'Dieta especial', 'Atenolol', 'Evitar esforços físicos', 419),
(439, 'Terapia ocupacional', 'Antidepressivos', 'Monitorar glicemia', 420),
(440, 'Dieta especial', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 421),
(441, 'Controle de diabetes', 'Hormônios', 'Revisão em 3 meses', 422),
(442, 'Dieta balanceada', 'Suplementos', 'Consulta com nutricionista', 423),
(443, 'Dieta balanceada', 'Anti-inflamatórios', 'Retorno em 30 dias', 424),
(444, 'Dieta especial', 'Suplementos', 'Monitorar glicemia', 425),
(445, 'Iniciar tratamento', 'Suplementos', 'Revisão em 3 meses', 426),
(446, 'Controle hormonal', 'Hormônios', 'Verificar pressão diariamente', 427),
(447, 'Controle de diabetes', 'Hormônios', 'Retorno em 30 dias', 428),
(448, 'Terapia intensiva', 'Antidepressivos', 'Revisão em 6 meses', 429),
(449, 'Dieta especial', 'Suplementos vitamínicos', 'Monitorar glicemia', 430),
(450, 'Revisão médica', 'Hormônios', 'Sessões semanais', 431),
(451, 'Revisão médica', 'Hormônios', 'Monitorar glicemia', 432),
(452, 'Dieta balanceada', 'Anti-inflamatórios', 'Consulta com nutricionista', 433),
(453, 'Terapia intensiva', 'Novos medicamentos', 'Revisão em 6 meses', 434),
(454, 'Dieta balanceada', 'Suplementos vitamínicos', 'Avaliar em 60 dias', 435),
(455, 'Revisão médica', 'Novos medicamentos', 'Evitar esforços físicos', 436),
(456, 'Ajuste de medicamentos', 'Anti-inflamatórios', 'Evitar esforços físicos', 437),
(457, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 438),
(458, 'Fisioterapia', 'Antidepressivos', 'Consulta com nutricionista', 439),
(459, 'Revisão médica', 'Cremes dermatológicos', 'Revisão em 6 meses', 440),
(460, 'Novo óculos', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 441),
(461, 'Avaliação psicológica', 'Insulina', 'Monitorar glicemia', 442),
(462, 'Sessões de terapia', 'Lentes corretivas', 'Sessões semanais', 443),
(463, 'Dieta balanceada', 'Suplementos', 'Verificar pressão diariamente', 444),
(464, 'Fisioterapia', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 445),
(465, 'Dieta especial', 'Hormônios', 'Consulta com nutricionista', 446),
(466, 'Dieta balanceada', 'Antidepressivos', 'Monitorar glicemia', 447),
(467, 'Terapia intensiva', 'Cremes dermatológicos', 'Revisão em 6 meses', 448),
(468, 'Dieta especial', 'Novos medicamentos', 'Avaliar em 60 dias', 449),
(469, 'Avaliação psicológica', 'Anti-inflamatórios', 'Retorno em 30 dias', 450),
(470, 'Terapia ocupacional', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 451),
(471, 'Terapia intensiva', 'Anti-inflamatórios', 'Revisão em 3 meses', 452),
(472, 'Fisioterapia', 'Insulina', 'Monitorar glicemia', 453),
(473, 'Revisão médica', 'Antidepressivos', 'Retorno em 30 dias', 454),
(474, 'Dieta balanceada', 'Insulina', 'Consulta com nutricionista', 455),
(475, 'Dieta balanceada', 'Hormônios', 'Avaliar em 60 dias', 456),
(476, 'Novo óculos', 'Antidepressivos', 'Sessões semanais', 457),
(477, 'Ajuste de medicação', 'Óculos novos', 'Retorno em 30 dias', 458),
(478, 'Dieta especial', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 459),
(479, 'Novo óculos', 'Cremes dermatológicos', 'Evitar esforços físicos', 460),
(480, 'Sessões de terapia', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 461),
(481, 'Terapia intensiva', 'Hormônios', 'Revisão em 3 meses', 462),
(482, 'Controle de dieta', 'Insulina', 'Avaliar em 60 dias', 463),
(483, 'Controle hormonal', 'Insulina', 'Monitorar glicemia', 464),
(484, 'Sessões de terapia', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 465),
(485, 'Revisão médica', 'Lentes corretivas', 'Evitar esforços físicos', 466),
(486, 'Avaliação psicológica', 'Antidepressivos', 'Evitar esforços físicos', 467),
(487, 'Dieta especial', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 468),
(488, 'Controle de dieta', 'Insulina', 'Verificar pressão diariamente', 469),
(489, 'Revisão do tratamento', 'Lentes corretivas', 'Evitar esforços físicos', 470),
(490, 'Revisão médica', 'Anti-inflamatórios', 'Evitar esforços físicos', 471),
(491, 'Controle hormonal', 'Suplementos', 'Retorno em 15 dias', 472),
(492, 'Dieta especial', 'Anti-inflamatórios', 'Verificar pressão diariamente', 473),
(493, 'Dieta especial', 'Suplementos vitamínicos', 'Consulta com nutricionista', 474),
(494, 'Controle hormonal', 'Antidepressivos', 'Verificar pressão diariamente', 475),
(495, 'Iniciar tratamento', 'Insulina', 'Monitorar glicemia', 476),
(496, 'Iniciar tratamento', 'Novos medicamentos', 'Avaliar em 60 dias', 477),
(497, 'Correção de miopia', 'Novos medicamentos', 'Evitar esforços físicos', 478),
(498, 'Sessões de terapia', 'Antidepressivos', 'Revisão em 3 meses', 479),
(499, 'Dieta especial', 'Suplementos vitamínicos', 'Retorno em 15 dias', 480),
(500, 'Iniciar tratamento', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 481),
(501, 'Correção de miopia', 'Suplementos', 'Evitar esforços físicos', 482),
(502, 'Correção de miopia', 'Óculos novos', 'Retorno em 30 dias', 483),
(503, 'Avaliação psicológica', 'Anti-inflamatórios', 'Consulta com nutricionista', 484),
(504, 'Sessões de terapia', 'Cremes dermatológicos', 'Consulta com nutricionista', 485),
(505, 'Controle de dieta', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 486),
(506, 'Controle hormonal', 'Antidepressivos', 'Verificar pressão diariamente', 487),
(507, 'Ajuste de medicação', 'Anti-inflamatórios', 'Avaliar em 60 dias', 488),
(508, 'Novo óculos', 'Antidepressivos', 'Aplicar duas vezes ao dia', 489),
(509, 'Revisão do tratamento', 'Hormônios', 'Revisão em 6 meses', 490),
(510, 'Controle hormonal', 'Óculos novos', 'Avaliar em 60 dias', 491),
(511, 'Revisão do tratamento', 'Suplementos', 'Revisão em 3 meses', 492),
(512, 'Terapia intensiva', 'Hormônios', 'Aplicar duas vezes ao dia', 493),
(513, 'Dieta balanceada', 'Hormônios', 'Retorno em 15 dias', 494),
(514, 'Fisioterapia', 'Insulina', 'Avaliar em 60 dias', 495),
(515, 'Terapia intensiva', 'Atenolol', 'Evitar esforços físicos', 496),
(516, 'Avaliação psicológica', 'Suplementos vitamínicos', 'Revisão em 3 meses', 497),
(517, 'Controle de dieta', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 498),
(518, 'Dieta especial', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 499),
(519, 'Controle de dieta', 'Suplementos', 'Verificar pressão diariamente', 500),
(520, 'Uso de óculos', 'Hormônios', 'Evitar esforços físicos', 501),
(521, 'Uso de óculos', 'Insulina', 'Aplicar duas vezes ao dia', 502),
(522, 'Uso de óculos', 'Novos medicamentos', 'Retorno em 30 dias', 503),
(523, 'Dieta balanceada', 'Suplementos vitamínicos', 'Consulta com nutricionista', 504),
(524, 'Dieta balanceada', 'Suplementos vitamínicos', 'Retorno em 30 dias', 505),
(525, 'Avaliação psicológica', 'Cremes dermatológicos', 'Sessões semanais', 506),
(526, 'Revisão do tratamento', 'Óculos novos', 'Aplicar duas vezes ao dia', 507),
(527, 'Uso de óculos', 'Hormônios', 'Revisão em 6 meses', 508),
(528, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 509),
(529, 'Controle de diabetes', 'Atenolol', 'Revisão em 3 meses', 510),
(530, 'Novo óculos', 'Anti-inflamatórios', 'Retorno em 30 dias', 511),
(531, 'Uso de óculos', 'Insulina', 'Revisão em 6 meses', 512),
(532, 'Sessões de terapia', 'Suplementos', 'Monitorar glicemia', 513),
(533, 'Terapia ocupacional', 'Lentes corretivas', 'Monitorar glicemia', 514),
(534, 'Dieta especial', 'Lentes corretivas', 'Monitorar glicemia', 515),
(535, 'Dieta balanceada', 'Novos medicamentos', 'Monitorar glicemia', 516),
(536, 'Dieta especial', 'Insulina', 'Monitorar glicemia', 517),
(537, 'Controle de dieta', 'Anti-inflamatórios', 'Retorno em 30 dias', 518),
(538, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Sessões semanais', 519),
(539, 'Controle de diabetes', 'Cremes dermatológicos', 'Avaliar em 60 dias', 520),
(540, 'Terapia ocupacional', 'Óculos novos', 'Aplicar duas vezes ao dia', 521),
(541, 'Controle hormonal', 'Atenolol', 'Retorno em 15 dias', 522),
(542, 'Avaliação psicológica', 'Suplementos', 'Revisão em 3 meses', 523),
(543, 'Correção de miopia', 'Cremes dermatológicos', 'Monitorar glicemia', 524),
(544, 'Novo óculos', 'Lentes corretivas', 'Evitar esforços físicos', 525),
(545, 'Correção de miopia', 'Novos medicamentos', 'Revisão em 3 meses', 526),
(546, 'Dieta especial', 'Antidepressivos', 'Monitorar glicemia', 527),
(547, 'Terapia intensiva', 'Novos medicamentos', 'Retorno em 30 dias', 528),
(548, 'Revisão do tratamento', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 529),
(549, 'Iniciar tratamento', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 530),
(550, 'Iniciar tratamento', 'Insulina', 'Avaliar em 60 dias', 531),
(551, 'Avaliação psicológica', 'Óculos novos', 'Evitar esforços físicos', 532),
(552, 'Sessões de terapia', 'Lentes corretivas', 'Consulta com nutricionista', 533),
(553, 'Correção de miopia', 'Antidepressivos', 'Retorno em 15 dias', 534),
(554, 'Iniciar tratamento', 'Hormônios', 'Avaliar em 60 dias', 535),
(555, 'Terapia intensiva', 'Antidepressivos', 'Verificar pressão diariamente', 536),
(556, 'Controle de diabetes', 'Antidepressivos', 'Avaliar em 60 dias', 537),
(557, 'Avaliação psicológica', 'Antidepressivos', 'Monitorar glicemia', 538),
(558, 'Ajuste de medicamentos', 'Suplementos', 'Verificar pressão diariamente', 539),
(559, 'Terapia intensiva', 'Lentes corretivas', 'Monitorar glicemia', 540),
(560, 'Novo óculos', 'Atenolol', 'Retorno em 30 dias', 541),
(561, 'Correção de miopia', 'Lentes corretivas', 'Consulta com nutricionista', 542),
(562, 'Correção de miopia', 'Lentes corretivas', 'Aplicar duas vezes ao dia', 543),
(563, 'Terapia ocupacional', 'Insulina', 'Avaliar em 60 dias', 544),
(564, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Evitar esforços físicos', 545),
(565, 'Controle hormonal', 'Cremes dermatológicos', 'Evitar esforços físicos', 546),
(566, 'Revisão médica', 'Antidepressivos', 'Aplicar duas vezes ao dia', 547),
(567, 'Iniciar tratamento', 'Óculos novos', 'Monitorar glicemia', 548),
(568, 'Dieta especial', 'Suplementos', 'Evitar esforços físicos', 549),
(569, 'Controle hormonal', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 550),
(570, 'Iniciar tratamento', 'Hormônios', 'Verificar pressão diariamente', 551),
(571, 'Dieta especial', 'Hormônios', 'Retorno em 15 dias', 552),
(572, 'Revisão médica', 'Anti-inflamatórios', 'Avaliar em 60 dias', 553),
(573, 'Controle hormonal', 'Novos medicamentos', 'Verificar pressão diariamente', 554),
(574, 'Ajuste de medicamentos', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 555),
(575, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 556),
(576, 'Avaliação psicológica', 'Antidepressivos', 'Revisão em 6 meses', 557),
(577, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Monitorar glicemia', 558),
(578, 'Correção de miopia', 'Óculos novos', 'Sessões semanais', 559),
(579, 'Revisão do tratamento', 'Atenolol', 'Revisão em 6 meses', 560),
(580, 'Terapia intensiva', 'Atenolol', 'Evitar esforços físicos', 561),
(581, 'Uso de óculos', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 562),
(582, 'Terapia intensiva', 'Óculos novos', 'Consulta com nutricionista', 563),
(583, 'Terapia intensiva', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 564),
(584, 'Ajuste de medicação', 'Hormônios', 'Aplicar duas vezes ao dia', 565),
(585, 'Novo óculos', 'Suplementos vitamínicos', 'Sessões semanais', 566),
(586, 'Controle hormonal', 'Insulina', 'Retorno em 30 dias', 567),
(587, 'Iniciar tratamento', 'Cremes dermatológicos', 'Monitorar glicemia', 568),
(588, 'Controle de dieta', 'Antidepressivos', 'Retorno em 15 dias', 569),
(589, 'Novo óculos', 'Lentes corretivas', 'Evitar esforços físicos', 570),
(590, 'Revisão médica', 'Óculos novos', 'Revisão em 6 meses', 571),
(591, 'Fisioterapia', 'Anti-inflamatórios', 'Retorno em 15 dias', 572),
(592, 'Controle hormonal', 'Lentes corretivas', 'Revisão em 3 meses', 573),
(593, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Sessões semanais', 574),
(594, 'Iniciar tratamento', 'Suplementos vitamínicos', 'Retorno em 15 dias', 575),
(595, 'Controle de dieta', 'Atenolol', 'Consulta com nutricionista', 576),
(596, 'Novo óculos', 'Lentes corretivas', 'Consulta com nutricionista', 577),
(597, 'Dieta especial', 'Novos medicamentos', 'Revisão em 3 meses', 578),
(598, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Sessões semanais', 579),
(599, 'Ajuste de medicamentos', 'Novos medicamentos', 'Evitar esforços físicos', 580),
(600, 'Dieta balanceada', 'Óculos novos', 'Aplicar duas vezes ao dia', 581),
(601, 'Novo óculos', 'Atenolol', 'Evitar esforços físicos', 582),
(602, 'Ajuste de medicamentos', 'Antidepressivos', 'Aplicar duas vezes ao dia', 583),
(603, 'Controle de dieta', 'Anti-inflamatórios', 'Retorno em 15 dias', 584),
(604, 'Ajuste de medicamentos', 'Suplementos', 'Revisão em 6 meses', 585),
(605, 'Dieta balanceada', 'Suplementos vitamínicos', 'Sessões semanais', 586),
(606, 'Revisão médica', 'Cremes dermatológicos', 'Evitar esforços físicos', 587),
(607, 'Revisão do tratamento', 'Suplementos', 'Aplicar duas vezes ao dia', 588),
(608, 'Controle hormonal', 'Óculos novos', 'Sessões semanais', 589),
(609, 'Iniciar tratamento', 'Anti-inflamatórios', 'Avaliar em 60 dias', 590),
(610, 'Dieta balanceada', 'Suplementos vitamínicos', 'Retorno em 30 dias', 591),
(611, 'Dieta especial', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 592),
(612, 'Novo óculos', 'Óculos novos', 'Revisão em 6 meses', 593),
(613, 'Controle hormonal', 'Lentes corretivas', 'Retorno em 30 dias', 594),
(614, 'Correção de miopia', 'Insulina', 'Aplicar duas vezes ao dia', 595),
(615, 'Correção de miopia', 'Insulina', 'Consulta com nutricionista', 596),
(616, 'Dieta especial', 'Suplementos', 'Monitorar glicemia', 597),
(617, 'Novo óculos', 'Novos medicamentos', 'Evitar esforços físicos', 598),
(618, 'Correção de miopia', 'Cremes dermatológicos', 'Evitar esforços físicos', 599),
(619, 'Dieta especial', 'Anti-inflamatórios', 'Revisão em 3 meses', 600),
(620, 'Revisão médica', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 601),
(621, 'Controle hormonal', 'Lentes corretivas', 'Revisão em 3 meses', 602),
(622, 'Controle de diabetes', 'Óculos novos', 'Revisão em 6 meses', 603),
(623, 'Avaliação psicológica', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 604),
(624, 'Dieta balanceada', 'Antidepressivos', 'Sessões semanais', 605),
(625, 'Avaliação psicológica', 'Atenolol', 'Monitorar glicemia', 606),
(626, 'Terapia ocupacional', 'Novos medicamentos', 'Revisão em 6 meses', 607),
(627, 'Sessões de terapia', 'Antidepressivos', 'Revisão em 3 meses', 608),
(628, 'Ajuste de medicação', 'Cremes dermatológicos', 'Revisão em 6 meses', 609),
(629, 'Dieta especial', 'Óculos novos', 'Evitar esforços físicos', 610),
(630, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 611),
(631, 'Revisão do tratamento', 'Novos medicamentos', 'Consulta com nutricionista', 612),
(632, 'Iniciar tratamento', 'Atenolol', 'Retorno em 30 dias', 613),
(633, 'Sessões de terapia', 'Lentes corretivas', 'Sessões semanais', 614),
(634, 'Sessões de terapia', 'Suplementos vitamínicos', 'Revisão em 6 meses', 615),
(635, 'Novo óculos', 'Lentes corretivas', 'Revisão em 3 meses', 616),
(636, 'Terapia intensiva', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 617),
(637, 'Controle hormonal', 'Óculos novos', 'Sessões semanais', 618),
(638, 'Iniciar tratamento', 'Insulina', 'Verificar pressão diariamente', 619),
(639, 'Revisão do tratamento', 'Antidepressivos', 'Avaliar em 60 dias', 620),
(640, 'Fisioterapia', 'Novos medicamentos', 'Retorno em 30 dias', 621),
(641, 'Controle hormonal', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 622),
(642, 'Revisão médica', 'Insulina', 'Revisão em 3 meses', 623),
(643, 'Controle hormonal', 'Cremes dermatológicos', 'Sessões semanais', 624),
(644, 'Avaliação psicológica', 'Antidepressivos', 'Verificar pressão diariamente', 625),
(645, 'Controle hormonal', 'Anti-inflamatórios', 'Sessões semanais', 626),
(646, 'Revisão médica', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 627),
(647, 'Revisão do tratamento', 'Cremes dermatológicos', 'Consulta com nutricionista', 628),
(648, 'Dieta especial', 'Novos medicamentos', 'Verificar pressão diariamente', 629),
(649, 'Controle hormonal', 'Antidepressivos', 'Avaliar em 60 dias', 630),
(650, 'Terapia intensiva', 'Anti-inflamatórios', 'Avaliar em 60 dias', 631),
(651, 'Controle de dieta', 'Óculos novos', 'Monitorar glicemia', 632),
(652, 'Controle hormonal', 'Óculos novos', 'Consulta com nutricionista', 633),
(653, 'Novo óculos', 'Cremes dermatológicos', 'Retorno em 15 dias', 634),
(654, 'Dieta balanceada', 'Cremes dermatológicos', 'Sessões semanais', 635),
(655, 'Novo óculos', 'Óculos novos', 'Monitorar glicemia', 636),
(656, 'Controle de diabetes', 'Hormônios', 'Revisão em 3 meses', 637),
(657, 'Sessões de terapia', 'Atenolol', 'Evitar esforços físicos', 638),
(658, 'Fisioterapia', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 639),
(659, 'Controle hormonal', 'Novos medicamentos', 'Retorno em 15 dias', 640),
(660, 'Fisioterapia', 'Anti-inflamatórios', 'Revisão em 6 meses', 641),
(661, 'Correção de miopia', 'Anti-inflamatórios', 'Consulta com nutricionista', 642),
(662, 'Terapia intensiva', 'Insulina', 'Revisão em 6 meses', 643),
(663, 'Controle hormonal', 'Antidepressivos', 'Retorno em 30 dias', 644),
(664, 'Revisão do tratamento', 'Cremes dermatológicos', 'Evitar esforços físicos', 645),
(665, 'Dieta balanceada', 'Atenolol', 'Retorno em 30 dias', 646),
(666, 'Fisioterapia', 'Suplementos', 'Revisão em 3 meses', 647),
(667, 'Correção de miopia', 'Atenolol', 'Evitar esforços físicos', 648),
(668, 'Sessões de terapia', 'Novos medicamentos', 'Retorno em 15 dias', 649),
(669, 'Dieta especial', 'Anti-inflamatórios', 'Monitorar glicemia', 650),
(670, 'Dieta balanceada', 'Lentes corretivas', 'Revisão em 6 meses', 651),
(671, 'Novo óculos', 'Lentes corretivas', 'Avaliar em 60 dias', 652),
(672, 'Avaliação psicológica', 'Antidepressivos', 'Retorno em 30 dias', 653),
(673, 'Fisioterapia', 'Hormônios', 'Monitorar glicemia', 654),
(674, 'Terapia intensiva', 'Atenolol', 'Retorno em 30 dias', 655),
(675, 'Ajuste de medicação', 'Novos medicamentos', 'Evitar esforços físicos', 656),
(676, 'Dieta especial', 'Hormônios', 'Revisão em 6 meses', 657),
(677, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Retorno em 30 dias', 658),
(678, 'Dieta especial', 'Suplementos vitamínicos', 'Monitorar glicemia', 659),
(679, 'Controle de diabetes', 'Atenolol', 'Avaliar em 60 dias', 660),
(680, 'Dieta balanceada', 'Suplementos', 'Avaliar em 60 dias', 661),
(681, 'Avaliação psicológica', 'Hormônios', 'Revisão em 3 meses', 662),
(682, 'Uso de óculos', 'Cremes dermatológicos', 'Evitar esforços físicos', 663),
(683, 'Terapia ocupacional', 'Cremes dermatológicos', 'Sessões semanais', 664),
(684, 'Controle de dieta', 'Antidepressivos', 'Revisão em 6 meses', 665),
(685, 'Novo óculos', 'Suplementos vitamínicos', 'Evitar esforços físicos', 666),
(686, 'Controle de dieta', 'Antidepressivos', 'Avaliar em 60 dias', 667),
(687, 'Controle de diabetes', 'Óculos novos', 'Avaliar em 60 dias', 668),
(688, 'Ajuste de medicação', 'Óculos novos', 'Retorno em 30 dias', 669),
(689, 'Uso de óculos', 'Atenolol', 'Evitar esforços físicos', 670),
(690, 'Controle hormonal', 'Hormônios', 'Avaliar em 60 dias', 671),
(691, 'Dieta balanceada', 'Lentes corretivas', 'Revisão em 6 meses', 672),
(692, 'Controle hormonal', 'Antidepressivos', 'Revisão em 6 meses', 673),
(693, 'Ajuste de medicamentos', 'Atenolol', 'Evitar esforços físicos', 674),
(694, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Avaliar em 60 dias', 675),
(695, 'Terapia intensiva', 'Novos medicamentos', 'Evitar esforços físicos', 676),
(696, 'Avaliação psicológica', 'Insulina', 'Aplicar duas vezes ao dia', 677),
(697, 'Dieta balanceada', 'Óculos novos', 'Aplicar duas vezes ao dia', 678),
(698, 'Controle hormonal', 'Anti-inflamatórios', 'Monitorar glicemia', 679),
(699, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Consulta com nutricionista', 680),
(700, 'Revisão médica', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 681),
(701, 'Novo óculos', 'Insulina', 'Verificar pressão diariamente', 682),
(702, 'Controle de dieta', 'Anti-inflamatórios', 'Avaliar em 60 dias', 683),
(703, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Revisão em 3 meses', 684),
(704, 'Controle hormonal', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 685),
(705, 'Sessões de terapia', 'Suplementos', 'Verificar pressão diariamente', 686),
(706, 'Fisioterapia', 'Antidepressivos', 'Revisão em 3 meses', 687),
(707, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 688),
(708, 'Terapia ocupacional', 'Hormônios', 'Retorno em 15 dias', 689),
(709, 'Controle de diabetes', 'Insulina', 'Retorno em 15 dias', 690),
(710, 'Iniciar tratamento', 'Insulina', 'Revisão em 6 meses', 691),
(711, 'Controle de diabetes', 'Novos medicamentos', 'Aplicar duas vezes ao dia', 692),
(712, 'Terapia intensiva', 'Suplementos', 'Retorno em 30 dias', 693),
(713, 'Fisioterapia', 'Insulina', 'Monitorar glicemia', 694),
(714, 'Dieta especial', 'Lentes corretivas', 'Retorno em 15 dias', 695),
(715, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 696),
(716, 'Controle hormonal', 'Insulina', 'Consulta com nutricionista', 697),
(717, 'Controle de dieta', 'Cremes dermatológicos', 'Monitorar glicemia', 698),
(718, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Sessões semanais', 699),
(719, 'Ajuste de medicação', 'Novos medicamentos', 'Revisão em 3 meses', 700),
(720, 'Controle de diabetes', 'Cremes dermatológicos', 'Avaliar em 60 dias', 701),
(721, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Sessões semanais', 702),
(722, 'Iniciar tratamento', 'Atenolol', 'Consulta com nutricionista', 703),
(723, 'Revisão do tratamento', 'Suplementos', 'Verificar pressão diariamente', 704),
(724, 'Uso de óculos', 'Cremes dermatológicos', 'Avaliar em 60 dias', 705),
(725, 'Iniciar tratamento', 'Antidepressivos', 'Revisão em 3 meses', 706),
(726, 'Revisão do tratamento', 'Atenolol', 'Revisão em 6 meses', 707),
(727, 'Terapia intensiva', 'Medicamentos para ansiedade', 'Sessões semanais', 708),
(728, 'Revisão médica', 'Novos medicamentos', 'Retorno em 15 dias', 709),
(729, 'Revisão do tratamento', 'Novos medicamentos', 'Sessões semanais', 710),
(730, 'Revisão médica', 'Anti-inflamatórios', 'Avaliar em 60 dias', 711),
(731, 'Controle de diabetes', 'Antidepressivos', 'Verificar pressão diariamente', 712),
(732, 'Dieta especial', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 713),
(733, 'Dieta balanceada', 'Atenolol', 'Avaliar em 60 dias', 714),
(734, 'Uso de óculos', 'Anti-inflamatórios', 'Sessões semanais', 715),
(735, 'Dieta especial', 'Novos medicamentos', 'Retorno em 30 dias', 716),
(736, 'Terapia ocupacional', 'Hormônios', 'Revisão em 6 meses', 717),
(737, 'Correção de miopia', 'Atenolol', 'Monitorar glicemia', 718),
(738, 'Controle hormonal', 'Óculos novos', 'Retorno em 15 dias', 719),
(739, 'Controle hormonal', 'Óculos novos', 'Revisão em 6 meses', 720),
(740, 'Controle hormonal', 'Óculos novos', 'Revisão em 6 meses', 721),
(741, 'Terapia intensiva', 'Suplementos', 'Evitar esforços físicos', 722),
(742, 'Controle hormonal', 'Antidepressivos', 'Verificar pressão diariamente', 723),
(743, 'Terapia intensiva', 'Hormônios', 'Evitar esforços físicos', 724),
(744, 'Terapia ocupacional', 'Lentes corretivas', 'Evitar esforços físicos', 725),
(745, 'Fisioterapia', 'Suplementos vitamínicos', 'Avaliar em 60 dias', 726),
(746, 'Dieta balanceada', 'Novos medicamentos', 'Revisão em 3 meses', 727),
(747, 'Controle hormonal', 'Cremes dermatológicos', 'Retorno em 15 dias', 728),
(748, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 729),
(749, 'Terapia intensiva', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 730),
(750, 'Controle de dieta', 'Suplementos', 'Aplicar duas vezes ao dia', 731),
(751, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 732),
(752, 'Correção de miopia', 'Lentes corretivas', 'Sessões semanais', 733),
(753, 'Ajuste de medicação', 'Antidepressivos', 'Sessões semanais', 734),
(754, 'Correção de miopia', 'Suplementos vitamínicos', 'Retorno em 30 dias', 735),
(755, 'Terapia intensiva', 'Insulina', 'Revisão em 3 meses', 736),
(756, 'Revisão médica', 'Antidepressivos', 'Retorno em 15 dias', 737),
(757, 'Uso de óculos', 'Novos medicamentos', 'Evitar esforços físicos', 738),
(758, 'Avaliação psicológica', 'Novos medicamentos', 'Verificar pressão diariamente', 739),
(759, 'Iniciar tratamento', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 740),
(760, 'Revisão médica', 'Anti-inflamatórios', 'Consulta com nutricionista', 741),
(761, 'Ajuste de medicação', 'Insulina', 'Aplicar duas vezes ao dia', 742),
(762, 'Terapia intensiva', 'Óculos novos', 'Revisão em 6 meses', 743),
(763, 'Controle hormonal', 'Anti-inflamatórios', 'Retorno em 30 dias', 744),
(764, 'Ajuste de medicamentos', 'Cremes dermatológicos', 'Verificar pressão diariamente', 745),
(765, 'Controle hormonal', 'Suplementos', 'Evitar esforços físicos', 746),
(766, 'Ajuste de medicação', 'Atenolol', 'Verificar pressão diariamente', 747),
(767, 'Revisão médica', 'Óculos novos', 'Evitar esforços físicos', 748),
(768, 'Terapia intensiva', 'Óculos novos', 'Consulta com nutricionista', 749),
(769, 'Controle hormonal', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 750),
(770, 'Sessões de terapia', 'Lentes corretivas', 'Avaliar em 60 dias', 751),
(771, 'Correção de miopia', 'Antidepressivos', 'Evitar esforços físicos', 752),
(772, 'Sessões de terapia', 'Suplementos vitamínicos', 'Retorno em 15 dias', 753),
(773, 'Fisioterapia', 'Suplementos vitamínicos', 'Consulta com nutricionista', 754),
(774, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Verificar pressão diariamente', 755),
(775, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 756),
(776, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Aplicar duas vezes ao dia', 757),
(777, 'Controle hormonal', 'Hormônios', 'Revisão em 3 meses', 758),
(778, 'Controle de diabetes', 'Novos medicamentos', 'Revisão em 3 meses', 759),
(779, 'Sessões de terapia', 'Insulina', 'Monitorar glicemia', 760),
(780, 'Controle hormonal', 'Suplementos', 'Monitorar glicemia', 761),
(781, 'Controle hormonal', 'Antidepressivos', 'Monitorar glicemia', 762),
(782, 'Ajuste de medicamentos', 'Anti-inflamatórios', 'Revisão em 6 meses', 763),
(783, 'Fisioterapia', 'Óculos novos', 'Verificar pressão diariamente', 764),
(784, 'Uso de óculos', 'Anti-inflamatórios', 'Avaliar em 60 dias', 765),
(785, 'Novo óculos', 'Lentes corretivas', 'Retorno em 30 dias', 766),
(786, 'Controle de dieta', 'Lentes corretivas', 'Retorno em 30 dias', 767),
(787, 'Controle hormonal', 'Suplementos vitamínicos', 'Consulta com nutricionista', 768),
(788, 'Revisão do tratamento', 'Novos medicamentos', 'Revisão em 3 meses', 769),
(789, 'Correção de miopia', 'Anti-inflamatórios', 'Verificar pressão diariamente', 770),
(790, 'Iniciar tratamento', 'Suplementos', 'Revisão em 3 meses', 771),
(791, 'Iniciar tratamento', 'Suplementos vitamínicos', 'Retorno em 15 dias', 772),
(792, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Monitorar glicemia', 773),
(793, 'Revisão do tratamento', 'Insulina', 'Aplicar duas vezes ao dia', 774),
(794, 'Avaliação psicológica', 'Cremes dermatológicos', 'Monitorar glicemia', 775),
(795, 'Ajuste de medicamentos', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 776),
(796, 'Controle de dieta', 'Óculos novos', 'Consulta com nutricionista', 777),
(797, 'Fisioterapia', 'Cremes dermatológicos', 'Retorno em 30 dias', 778),
(798, 'Terapia ocupacional', 'Atenolol', 'Revisão em 3 meses', 779),
(799, 'Novo óculos', 'Lentes corretivas', 'Evitar esforços físicos', 780),
(800, 'Novo óculos', 'Novos medicamentos', 'Monitorar glicemia', 781),
(801, 'Iniciar tratamento', 'Óculos novos', 'Retorno em 15 dias', 782),
(802, 'Terapia intensiva', 'Insulina', 'Retorno em 30 dias', 783),
(803, 'Controle hormonal', 'Insulina', 'Aplicar duas vezes ao dia', 784),
(804, 'Dieta especial', 'Cremes dermatológicos', 'Evitar esforços físicos', 785),
(805, 'Revisão do tratamento', 'Óculos novos', 'Retorno em 30 dias', 786),
(806, 'Revisão do tratamento', 'Anti-inflamatórios', 'Monitorar glicemia', 787),
(807, 'Iniciar tratamento', 'Suplementos vitamínicos', 'Avaliar em 60 dias', 788),
(808, 'Uso de óculos', 'Novos medicamentos', 'Revisão em 3 meses', 789),
(809, 'Controle hormonal', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 790),
(810, 'Terapia intensiva', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 791),
(811, 'Controle hormonal', 'Cremes dermatológicos', 'Consulta com nutricionista', 792),
(812, 'Dieta balanceada', 'Cremes dermatológicos', 'Avaliar em 60 dias', 793),
(813, 'Ajuste de medicamentos', 'Novos medicamentos', 'Sessões semanais', 794),
(814, 'Fisioterapia', 'Insulina', 'Avaliar em 60 dias', 795),
(815, 'Iniciar tratamento', 'Óculos novos', 'Retorno em 30 dias', 796),
(816, 'Controle hormonal', 'Hormônios', 'Retorno em 30 dias', 797),
(817, 'Controle de dieta', 'Cremes dermatológicos', 'Revisão em 3 meses', 798),
(818, 'Dieta especial', 'Lentes corretivas', 'Monitorar glicemia', 799),
(819, 'Avaliação psicológica', 'Insulina', 'Revisão em 6 meses', 800),
(820, 'Dieta especial', 'Óculos novos', 'Consulta com nutricionista', 801),
(821, 'Revisão do tratamento', 'Óculos novos', 'Revisão em 6 meses', 802),
(822, 'Iniciar tratamento', 'Novos medicamentos', 'Revisão em 6 meses', 803),
(823, 'Fisioterapia', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 804),
(824, 'Novo óculos', 'Suplementos vitamínicos', 'Verificar pressão diariamente', 805),
(825, 'Revisão do tratamento', 'Hormônios', 'Evitar esforços físicos', 806),
(826, 'Revisão do tratamento', 'Cremes dermatológicos', 'Verificar pressão diariamente', 807),
(827, 'Iniciar tratamento', 'Lentes corretivas', 'Avaliar em 60 dias', 808),
(828, 'Controle hormonal', 'Atenolol', 'Consulta com nutricionista', 809),
(829, 'Revisão do tratamento', 'Atenolol', 'Revisão em 3 meses', 810),
(830, 'Dieta especial', 'Anti-inflamatórios', 'Avaliar em 60 dias', 811),
(831, 'Iniciar tratamento', 'Antidepressivos', 'Evitar esforços físicos', 812),
(832, 'Fisioterapia', 'Insulina', 'Retorno em 30 dias', 813),
(833, 'Fisioterapia', 'Óculos novos', 'Consulta com nutricionista', 814),
(834, 'Sessões de terapia', 'Anti-inflamatórios', 'Aplicar duas vezes ao dia', 815),
(835, 'Novo óculos', 'Óculos novos', 'Revisão em 6 meses', 816),
(836, 'Sessões de terapia', 'Insulina', 'Retorno em 30 dias', 817),
(837, 'Ajuste de medicação', 'Insulina', 'Aplicar duas vezes ao dia', 818),
(838, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Retorno em 30 dias', 819),
(839, 'Revisão médica', 'Hormônios', 'Evitar esforços físicos', 820),
(840, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Monitorar glicemia', 821),
(841, 'Novo óculos', 'Cremes dermatológicos', 'Revisão em 6 meses', 822),
(842, 'Ajuste de medicamentos', 'Hormônios', 'Verificar pressão diariamente', 823),
(843, 'Uso de óculos', 'Lentes corretivas', 'Verificar pressão diariamente', 824),
(844, 'Dieta especial', 'Cremes dermatológicos', 'Revisão em 6 meses', 825),
(845, 'Terapia ocupacional', 'Suplementos', 'Evitar esforços físicos', 826),
(846, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Evitar esforços físicos', 827),
(847, 'Dieta especial', 'Lentes corretivas', 'Verificar pressão diariamente', 828),
(848, 'Revisão do tratamento', 'Lentes corretivas', 'Verificar pressão diariamente', 829),
(849, 'Terapia intensiva', 'Atenolol', 'Retorno em 15 dias', 830),
(850, 'Dieta balanceada', 'Hormônios', 'Evitar esforços físicos', 831),
(851, 'Revisão médica', 'Medicamentos para ansiedade', 'Monitorar glicemia', 832),
(852, 'Dieta balanceada', 'Suplementos', 'Evitar esforços físicos', 833),
(853, 'Revisão do tratamento', 'Cremes dermatológicos', 'Retorno em 15 dias', 834),
(854, 'Novo óculos', 'Antidepressivos', 'Aplicar duas vezes ao dia', 835),
(855, 'Novo óculos', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 836),
(856, 'Terapia ocupacional', 'Lentes corretivas', 'Revisão em 3 meses', 837),
(857, 'Controle hormonal', 'Insulina', 'Retorno em 30 dias', 838),
(858, 'Controle hormonal', 'Suplementos', 'Consulta com nutricionista', 839),
(859, 'Correção de miopia', 'Insulina', 'Revisão em 3 meses', 840),
(860, 'Controle hormonal', 'Suplementos', 'Sessões semanais', 841),
(861, 'Ajuste de medicação', 'Antidepressivos', 'Avaliar em 60 dias', 842),
(862, 'Revisão do tratamento', 'Novos medicamentos', 'Retorno em 30 dias', 843),
(863, 'Novo óculos', 'Cremes dermatológicos', 'Sessões semanais', 844),
(864, 'Ajuste de medicação', 'Novos medicamentos', 'Retorno em 15 dias', 845),
(865, 'Revisão do tratamento', 'Hormônios', 'Sessões semanais', 846),
(866, 'Revisão do tratamento', 'Anti-inflamatórios', 'Revisão em 6 meses', 847),
(867, 'Revisão médica', 'Suplementos vitamínicos', 'Retorno em 30 dias', 848),
(868, 'Dieta balanceada', 'Óculos novos', 'Aplicar duas vezes ao dia', 849),
(869, 'Fisioterapia', 'Hormônios', 'Consulta com nutricionista', 850),
(870, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Consulta com nutricionista', 851),
(871, 'Ajuste de medicação', 'Hormônios', 'Revisão em 3 meses', 852),
(872, 'Iniciar tratamento', 'Cremes dermatológicos', 'Verificar pressão diariamente', 853),
(873, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 854),
(874, 'Ajuste de medicamentos', 'Suplementos vitamínicos', 'Avaliar em 60 dias', 855),
(875, 'Ajuste de medicamentos', 'Suplementos', 'Verificar pressão diariamente', 856),
(876, 'Iniciar tratamento', 'Hormônios', 'Verificar pressão diariamente', 857),
(877, 'Dieta balanceada', 'Atenolol', 'Aplicar duas vezes ao dia', 858),
(878, 'Novo óculos', 'Hormônios', 'Avaliar em 60 dias', 859),
(879, 'Controle hormonal', 'Atenolol', 'Monitorar glicemia', 860),
(880, 'Novo óculos', 'Anti-inflamatórios', 'Evitar esforços físicos', 861),
(881, 'Revisão do tratamento', 'Antidepressivos', 'Retorno em 30 dias', 862),
(882, 'Ajuste de medicamentos', 'Atenolol', 'Revisão em 3 meses', 863),
(883, 'Uso de óculos', 'Óculos novos', 'Consulta com nutricionista', 864),
(884, 'Dieta especial', 'Óculos novos', 'Retorno em 15 dias', 865),
(885, 'Controle de dieta', 'Cremes dermatológicos', 'Evitar esforços físicos', 866),
(886, 'Avaliação psicológica', 'Suplementos', 'Retorno em 30 dias', 867),
(887, 'Avaliação psicológica', 'Óculos novos', 'Sessões semanais', 868),
(888, 'Dieta balanceada', 'Insulina', 'Revisão em 3 meses', 869),
(889, 'Uso de óculos', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 870),
(890, 'Controle hormonal', 'Lentes corretivas', 'Monitorar glicemia', 871),
(891, 'Terapia ocupacional', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 872),
(892, 'Dieta balanceada', 'Anti-inflamatórios', 'Consulta com nutricionista', 873),
(893, 'Correção de miopia', 'Anti-inflamatórios', 'Monitorar glicemia', 874),
(894, 'Ajuste de medicamentos', 'Insulina', 'Retorno em 30 dias', 875),
(895, 'Controle hormonal', 'Antidepressivos', 'Sessões semanais', 876),
(896, 'Terapia intensiva', 'Cremes dermatológicos', 'Evitar esforços físicos', 877),
(897, 'Uso de óculos', 'Hormônios', 'Avaliar em 60 dias', 878),
(898, 'Avaliação psicológica', 'Lentes corretivas', 'Evitar esforços físicos', 879),
(899, 'Correção de miopia', 'Anti-inflamatórios', 'Consulta com nutricionista', 880),
(900, 'Dieta balanceada', 'Medicamentos para ansiedade', 'Aplicar duas vezes ao dia', 881),
(901, 'Controle de dieta', 'Atenolol', 'Avaliar em 60 dias', 882),
(902, 'Ajuste de medicamentos', 'Hormônios', 'Evitar esforços físicos', 883),
(903, 'Dieta balanceada', 'Cremes dermatológicos', 'Retorno em 30 dias', 884),
(904, 'Revisão do tratamento', 'Novos medicamentos', 'Monitorar glicemia', 885),
(905, 'Correção de miopia', 'Insulina', 'Sessões semanais', 886),
(906, 'Sessões de terapia', 'Suplementos', 'Retorno em 15 dias', 887),
(907, 'Ajuste de medicação', 'Medicamentos para ansiedade', 'Evitar esforços físicos', 888),
(908, 'Terapia ocupacional', 'Hormônios', 'Avaliar em 60 dias', 889),
(909, 'Controle hormonal', 'Novos medicamentos', 'Consulta com nutricionista', 890),
(910, 'Revisão do tratamento', 'Óculos novos', 'Sessões semanais', 891),
(911, 'Ajuste de medicamentos', 'Hormônios', 'Sessões semanais', 892),
(912, 'Revisão do tratamento', 'Hormônios', 'Aplicar duas vezes ao dia', 893),
(913, 'Uso de óculos', 'Cremes dermatológicos', 'Revisão em 3 meses', 894),
(914, 'Correção de miopia', 'Atenolol', 'Avaliar em 60 dias', 895),
(915, 'Novo óculos', 'Óculos novos', 'Retorno em 15 dias', 896),
(916, 'Dieta especial', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 897),
(917, 'Dieta balanceada', 'Novos medicamentos', 'Evitar esforços físicos', 898),
(918, 'Terapia ocupacional', 'Antidepressivos', 'Retorno em 30 dias', 899),
(919, 'Controle hormonal', 'Atenolol', 'Retorno em 15 dias', 900),
(920, 'Controle de diabetes', 'Anti-inflamatórios', 'Sessões semanais', 901),
(921, 'Controle de diabetes', 'Atenolol', 'Aplicar duas vezes ao dia', 902),
(922, 'Sessões de terapia', 'Anti-inflamatórios', 'Retorno em 30 dias', 903),
(923, 'Sessões de terapia', 'Lentes corretivas', 'Revisão em 6 meses', 904),
(924, 'Novo óculos', 'Cremes dermatológicos', 'Consulta com nutricionista', 905),
(925, 'Ajuste de medicação', 'Novos medicamentos', 'Verificar pressão diariamente', 906),
(926, 'Controle de dieta', 'Hormônios', 'Revisão em 6 meses', 907),
(927, 'Ajuste de medicamentos', 'Insulina', 'Retorno em 15 dias', 908),
(928, 'Controle hormonal', 'Hormônios', 'Retorno em 15 dias', 909),
(929, 'Ajuste de medicação', 'Cremes dermatológicos', 'Avaliar em 60 dias', 910),
(930, 'Revisão médica', 'Anti-inflamatórios', 'Monitorar glicemia', 911),
(931, 'Ajuste de medicamentos', 'Hormônios', 'Verificar pressão diariamente', 912),
(932, 'Controle de diabetes', 'Óculos novos', 'Retorno em 30 dias', 913),
(933, 'Terapia intensiva', 'Cremes dermatológicos', 'Monitorar glicemia', 914),
(934, 'Terapia intensiva', 'Anti-inflamatórios', 'Evitar esforços físicos', 915),
(935, 'Ajuste de medicamentos', 'Suplementos', 'Retorno em 30 dias', 916),
(936, 'Novo óculos', 'Lentes corretivas', 'Retorno em 15 dias', 917),
(937, 'Sessões de terapia', 'Cremes dermatológicos', 'Evitar esforços físicos', 918),
(938, 'Ajuste de medicamentos', 'Hormônios', 'Retorno em 15 dias', 919),
(939, 'Uso de óculos', 'Óculos novos', 'Revisão em 6 meses', 920),
(940, 'Fisioterapia', 'Antidepressivos', 'Retorno em 15 dias', 921),
(941, 'Sessões de terapia', 'Suplementos vitamínicos', 'Monitorar glicemia', 922),
(942, 'Terapia ocupacional', 'Anti-inflamatórios', 'Avaliar em 60 dias', 923),
(943, 'Fisioterapia', 'Antidepressivos', 'Retorno em 30 dias', 924),
(944, 'Fisioterapia', 'Insulina', 'Sessões semanais', 925),
(945, 'Dieta especial', 'Novos medicamentos', 'Revisão em 6 meses', 926),
(946, 'Dieta especial', 'Insulina', 'Revisão em 6 meses', 927),
(947, 'Revisão do tratamento', 'Novos medicamentos', 'Sessões semanais', 928),
(948, 'Terapia intensiva', 'Antidepressivos', 'Retorno em 15 dias', 929),
(949, 'Dieta balanceada', 'Suplementos vitamínicos', 'Monitorar glicemia', 930),
(950, 'Controle hormonal', 'Óculos novos', 'Sessões semanais', 931),
(951, 'Dieta especial', 'Atenolol', 'Revisão em 3 meses', 932),
(952, 'Controle hormonal', 'Hormônios', 'Sessões semanais', 933),
(953, 'Dieta especial', 'Suplementos vitamínicos', 'Revisão em 3 meses', 934),
(954, 'Dieta especial', 'Óculos novos', 'Retorno em 30 dias', 935),
(955, 'Correção de miopia', 'Cremes dermatológicos', 'Revisão em 3 meses', 936),
(956, 'Ajuste de medicamentos', 'Novos medicamentos', 'Consulta com nutricionista', 937),
(957, 'Fisioterapia', 'Hormônios', 'Aplicar duas vezes ao dia', 938),
(958, 'Fisioterapia', 'Medicamentos para ansiedade', 'Retorno em 15 dias', 939),
(959, 'Ajuste de medicação', 'Cremes dermatológicos', 'Retorno em 30 dias', 940),
(960, 'Ajuste de medicação', 'Suplementos vitamínicos', 'Evitar esforços físicos', 941),
(961, 'Terapia ocupacional', 'Hormônios', 'Retorno em 30 dias', 942),
(962, 'Dieta especial', 'Novos medicamentos', 'Retorno em 15 dias', 943),
(963, 'Ajuste de medicamentos', 'Medicamentos para ansiedade', 'Revisão em 3 meses', 944),
(964, 'Avaliação psicológica', 'Antidepressivos', 'Verificar pressão diariamente', 945),
(965, 'Dieta balanceada', 'Suplementos', 'Evitar esforços físicos', 946),
(966, 'Controle hormonal', 'Novos medicamentos', 'Consulta com nutricionista', 947),
(967, 'Dieta especial', 'Medicamentos para ansiedade', 'Avaliar em 60 dias', 948),
(968, 'Revisão do tratamento', 'Óculos novos', 'Sessões semanais', 949),
(969, 'Controle de dieta', 'Insulina', 'Consulta com nutricionista', 950),
(970, 'Terapia intensiva', 'Óculos novos', 'Revisão em 6 meses', 951),
(971, 'Dieta balanceada', 'Óculos novos', 'Aplicar duas vezes ao dia', 952),
(972, 'Controle hormonal', 'Novos medicamentos', 'Avaliar em 60 dias', 953),
(973, 'Sessões de terapia', 'Novos medicamentos', 'Consulta com nutricionista', 954),
(974, 'Controle de diabetes', 'Lentes corretivas', 'Evitar esforços físicos', 955),
(975, 'Controle hormonal', 'Antidepressivos', 'Verificar pressão diariamente', 956),
(976, 'Novo óculos', 'Novos medicamentos', 'Consulta com nutricionista', 957),
(977, 'Uso de óculos', 'Óculos novos', 'Retorno em 30 dias', 958),
(978, 'Revisão médica', 'Anti-inflamatórios', 'Consulta com nutricionista', 959),
(979, 'Dieta especial', 'Novos medicamentos', 'Retorno em 15 dias', 960),
(980, 'Correção de miopia', 'Cremes dermatológicos', 'Revisão em 3 meses', 961),
(981, 'Terapia intensiva', 'Óculos novos', 'Consulta com nutricionista', 962),
(982, 'Correção de miopia', 'Novos medicamentos', 'Retorno em 15 dias', 963),
(983, 'Controle hormonal', 'Anti-inflamatórios', 'Revisão em 6 meses', 964),
(984, 'Controle hormonal', 'Insulina', 'Monitorar glicemia', 965),
(985, 'Controle hormonal', 'Insulina', 'Revisão em 3 meses', 966),
(986, 'Terapia intensiva', 'Suplementos', 'Evitar esforços físicos', 967),
(987, 'Controle hormonal', 'Óculos novos', 'Monitorar glicemia', 968),
(988, 'Correção de miopia', 'Cremes dermatológicos', 'Avaliar em 60 dias', 969),
(989, 'Dieta especial', 'Suplementos', 'Revisão em 6 meses', 970),
(990, 'Revisão do tratamento', 'Atenolol', 'Aplicar duas vezes ao dia', 971),
(991, 'Revisão médica', 'Novos medicamentos', 'Verificar pressão diariamente', 972),
(992, 'Avaliação psicológica', 'Hormônios', 'Monitorar glicemia', 973),
(993, 'Dieta balanceada', 'Insulina', 'Avaliar em 60 dias', 974),
(994, 'Iniciar tratamento', 'Antidepressivos', 'Aplicar duas vezes ao dia', 975),
(995, 'Dieta balanceada', 'Suplementos', 'Avaliar em 60 dias', 976),
(996, 'Dieta especial', 'Novos medicamentos', 'Verificar pressão diariamente', 977),
(997, 'Controle de dieta', 'Atenolol', 'Avaliar em 60 dias', 978),
(998, 'Controle hormonal', 'Medicamentos para ansiedade', 'Monitorar glicemia', 979),
(999, 'Sessões de terapia', 'Antidepressivos', 'Aplicar duas vezes ao dia', 980),
(1000, 'Sessões de terapia', 'Antidepressivos', 'Avaliar em 60 dias', 981),
(1001, 'Sessões de terapia', 'Suplementos', 'Aplicar duas vezes ao dia', 982),
(1002, 'Controle de dieta', 'Cremes dermatológicos', 'Aplicar duas vezes ao dia', 983),
(1003, 'Controle hormonal', 'Suplementos', 'Retorno em 15 dias', 984),
(1004, 'Sessões de terapia', 'Suplementos vitamínicos', 'Consulta com nutricionista', 985),
(1005, 'Fisioterapia', 'Novos medicamentos', 'Retorno em 15 dias', 986),
(1006, 'Avaliação psicológica', 'Hormônios', 'Monitorar glicemia', 987),
(1007, 'Terapia ocupacional', 'Lentes corretivas', 'Retorno em 30 dias', 988),
(1008, 'Novo óculos', 'Óculos novos', 'Retorno em 30 dias', 989),
(1009, 'Dieta especial', 'Medicamentos para ansiedade', 'Retorno em 30 dias', 990),
(1010, 'Dieta especial', 'Insulina', 'Revisão em 3 meses', 991),
(1011, 'Revisão médica', 'Suplementos vitamínicos', 'Evitar esforços físicos', 992),
(1012, 'Novo óculos', 'Lentes corretivas', 'Avaliar em 60 dias', 993),
(1013, 'Uso de óculos', 'Lentes corretivas', 'Consulta com nutricionista', 994),
(1014, 'Ajuste de medicamentos', 'Óculos novos', 'Evitar esforços físicos', 995),
(1015, 'Fisioterapia', 'Atenolol', 'Retorno em 30 dias', 996),
(1016, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Retorno em 30 dias', 997),
(1017, 'Fisioterapia', 'Suplementos', 'Verificar pressão diariamente', 998),
(1018, 'Dieta especial', 'Suplementos vitamínicos', 'Monitorar glicemia', 999),
(1019, 'Ajuste de medicação', 'Hormônios', 'Sessões semanais', 1000),
(1020, 'Correção de miopia', 'Óculos novos', 'Consulta com nutricionista', 1001),
(1021, 'Terapia intensiva', 'Suplementos vitamínicos', 'Evitar esforços físicos', 1002),
(1022, 'Novo óculos', 'Insulina', 'Aplicar duas vezes ao dia', 1003),
(1023, 'Controle hormonal', 'Lentes corretivas', 'Evitar esforços físicos', 1004),
(1024, 'Ajuste de medicação', 'Novos medicamentos', 'Revisão em 3 meses', 1005),
(1025, 'Ajuste de medicação', 'Atenolol', 'Verificar pressão diariamente', 1006),
(1026, 'Iniciar tratamento', 'Antidepressivos', 'Monitorar glicemia', 1007),
(1027, 'Uso de óculos', 'Medicamentos para ansiedade', 'Revisão em 6 meses', 1008),
(1028, 'Sessões de terapia', 'Atenolol', 'Monitorar glicemia', 1009),
(1029, 'Revisão do tratamento', 'Suplementos vitamínicos', 'Revisão em 3 meses', 1010),
(1030, 'Dieta balanceada', 'Lentes corretivas', 'Aplicar duas vezes ao dia', 1011);