CREATE TABLE IF NOT EXISTS MEDICO (
    CRM VARCHAR(12) NOT NULL,
    Nome VARCHAR(200) NOT NULL,
    Telefone VARCHAR(14) NOT NULL,
    Percentual DECIMAL(4, 2) NOT NULL,
    PRIMARY KEY(CRM)
);


CREATE TABLE IF NOT EXISTS  AGENDA (
    IdAgenda INT NOT NULL,
    DiaSemana VARCHAR(15) NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraFim TIME NOT NULL,
    CRM VARCHAR(12) NOT NULL,
    PRIMARY KEY (IdAgenda),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
);


CREATE TABLE IF NOT EXISTS  ESPECIALIDADE (
    IdEsp INT NOT NULL,
    NomeE VARCHAR(200) NOT NULL,
    Indice INT NOT NULL,
    PRIMARY KEY(IdEsp)
);

CREATE TABLE IF NOT EXISTS  EXERCE_ESPECIALIDADE (
    CRM VARCHAR(12) NOT NULL,
    IdEsp INT NOT NULL,
    FOREIGN KEY (IdEsp) REFERENCES ESPECIALIDADE (IdEsp),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
);

CREATE TABLE IF NOT EXISTS  CONSULTA (
    IdCon INT NOT NULL,
    CRM VARCHAR(12) NOT NULL,
    IdEsp INT NOT NULL,
    IdPac INT NOT NULL,
    Data DATE NOT NULL,
    HoraInicCon TIME NOT NULL,
    HoraFimCon TIME NOT NULL,
    Pagou INT,
    ValorPago DECIMAL(6,2),
    FormaPagamento VARCHAR(50),
    PRIMARY KEY (IdCon),
    FOREIGN KEY (IdEsp) REFERENCES ESPECIALIDADE (IdEsp),
    FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
	CONSTRAINT chk_pg CHECK (Pagou in (0, 1))
);
CREATE TABLE IF NOT EXISTS  PACIENTE (
    IdPac INT NOT NULL,
    CPF VARCHAR(14),
    NomeP VARCHAR(200) NOT NULL,
    TelefonePac VARCHAR(14) NOT NULL,
    Endereco VARCHAR(200),
    Idade INT,
    Sexo VARCHAR(1),
    PRIMARY KEY (IdPac),
    CONSTRAINT chk_sexo CHECK (UPPER(Sexo) in ('F', 'M'))
);

CREATE TABLE IF NOT EXISTS  DIAGNOSTICO (
    IdDiagnostico INT NOT NULL,
    TratamentoRecomendado VARCHAR(400) NOT NULL,
    RemediosReceitados VARCHAR(400),
    Observacoes VARCHAR(400),
    IdCon INT NOT NULL,
    PRIMARY KEY (IdDiagnostico),
    FOREIGN KEY (IdCon) REFERENCES CONSULTA (IdCon)
);

CREATE TABLE IF NOT EXISTS  DOENCA (
    IdDoenca INT NOT NULL,
    NomeD VARCHAR(200) NOT NULL,
    PRIMARY KEY (IdDoenca)
);

CREATE TABLE IF NOT EXISTS DIAGNOSTICA (
    IdDiagnostico INT NOT NULL,
    IdDoenca INT NOT NULL,
    FOREIGN KEY (IdDiagnostico) REFERENCES DIAGNOSTICO (IdDiagnostico),
    FOREIGN KEY (IdDoenca) REFERENCES DOENCA (IdDoenca)
);

